steps:
- name: 'docker:v19.3.10'
  args: [
            'buildx', 'build',
            '-t', 'gcr.io/$PROJECT_ID/swift-apis:latest',
            '-f', 'Dockerfile',
            '.'
        ]
options:
    env: ['DOCKER_CLI_EXPERIMENTAL=enabled']
images: ['gcr.io/$PROJECT_ID/swift-apis:latest']
timeout: 15000s

