steps:
- name: 'docker'
  args: ['info']
- name: 'docker'
  args: [
            'buildx', 'build',
            '-t', 'gcr.io/$PROJECT_ID/swift-apis:latest',
            '--cache-from', 'gcr.io/$PROJECT_ID/swift-apis:latest',
            '-f', 'Dockerfile',
            '.'
        ]
options:
  env: ['DOCKER_BUILDKIT=1', 'DOCKER_CLI_EXPERIMENTAL=enabled']
images: ['gcr.io/$PROJECT_ID/swift-apis:latest']
artifacts:
  objects:
    location: 'gs://gs.mak-play.com/$PROJECT_ID/swift-apis'
    paths: ['/BinaryCache/tensorflow-swift-apis/libtensorflow-prefix']
timeout: 15000s

