steps:
- name: 'gcr.io/cloud_builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    export DOCKER_BUILDKIT=1
- name: 'docker'
  args: [
            'build',
            '-t', 'gcr.io/$PROJECT_ID/swift-apis:latest',
            '--cache-from', 'gcr.io/$PROJECT_ID/swift-apis:latest',
            '-f', 'Dockerfile',
            '.'
        ]
images: ['gcr.io/$PROJECT_ID/swift-apis:latest']
timeout: 15000s

