steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
    - --destination=gcr.io/$PROJECT_ID/image
    - --cache=true
    - --cache-ttl=24h
    env:
    - 'AWS_ACCESS_KEY_ID=NOT_SET'
    - 'AWS_SECRET_KEY=NOT_SET'
timeout: 15000s

